### ISSUE TITLE
Current Backend Issues

### ISSUE THREAD

**Issue by gigimscarborough** [AnJuHyppolite/budgeting-app-backend#1]
- [x] Put route does not work. Returns an internal server error.
- [x] Why do you have react router in you backend?? You can uninstall unnecessary dependencies.
- [x] Your readme does not contain link to your deployed application and deployed api that I can see (Also the links to your API on canvas are incorrect. Your deployed url is https://tranquil-badlands-09117.herokuapp.com/transactions ).

**Comment by AnJuHyppolite** [comment]
Complete. Thank you, Gigi!
